name: Sync workspace

inputs:
  base_branch:
    description: Base branch
    required: true
    default: qcom-next-staging
  pr_number:
    description: PR number
    required: false
  topic_repo:
    description: Topic repository
    required: false
    default: qualcomm-linux/kernel-topics

runs:
  using: "composite"
  steps:
    - name: Print inputs
      shell: bash
      run: |
        echo ${{ inputs.base_branch }}
        echo ${{ inputs.pr_number }}

    - name: Checkout PR branch
      if: inputs.topic_repo == 'qualcomm-linux/kernel'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: qualcomm-linux/kernel
        ref: ${{ inputs.base_branch }}

    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Sync with latest changes
      if: inputs.topic_repo == 'qualcomm-linux/kernel'
      shell: bash
      run: |
        echo "Syncing with latest changes..."
        git fetch origin ${{ inputs.base_branch }}
        git merge origin/${{ inputs.base_branch }}

    - name: Clone repositories
      if: inputs.topic_repo == 'qualcomm-linux/kernel-topics'
      shell: bash
      run: |
        git clone https://github.com/qualcomm-linux/kernel.git
        git clone https://github.com/qualcomm-linux/automerge.git

    - name: Create merge configuration
      if: inputs.topic_repo == 'qualcomm-linux/kernel-topics'
      shell: bash
      run: |
        TOPIC_BRANCH=${{ inputs.base_branch }}
        TOPIC_REPO=${{ inputs.topic_repo }}
        cat <<EOF > merge.conf
        baseline https://github.com/qualcomm-linux/kernel.git qcom-next
        topic https://github.com/$TOPIC_REPO.git $TOPIC_BRANCH
        EOF
        echo "File 'merge.conf' created successfully."

    - name: Run auto merge
      if: inputs.topic_repo == 'qualcomm-linux/kernel-topics'
      shell: bash
      run: |
        cd kernel
        ../automerge/ci-merge -f ../merge.conf -t head -n

    - name: Fetch PR
      if: inputs.topic_repo == 'qualcomm-linux/kernel-topics'
      shell: bash
      run: |
        cd kernel
        git fetch https://github.com/${{inputs.topic_repo}}.git pull/${{inputs.pr_number}}/head:pr-${{inputs.pr_number}}
        git merge pr-${{inputs.pr_number}} --no-commit
        git commit -m "Merged PR ${{inputs.pr_number}}"
    
    - name: Fetch PR
      if: inputs.topic_repo == 'qualcomm-linux/kernel'
      shell: bash
      run: |
        git checkout ${{ inputs.base_branch }}
        git fetch https://github.com/qualcomm-linux/kernel.git pull/${{inputs.pr_number}}/head:pr-${{inputs.pr_number}}
        git merge pr-${{ inputs.pr_number }} --no-commit || echo "Merge already applied or fast-forwarded"
        if ! git diff --cached --quiet; then
          git commit -m "Merged PR #${{ inputs.pr_number }}"
        else
          echo "Nothing to commit. PR may already be merged or fast-forwarded."
        fi
