name: Kernel Checkers
on:
  workflow_call:
    inputs:
      check_name:
        required: true
        type: string
      kernel_src:
        required: true
        type: string
      base_sha:
        required: true
        type: string
      head_sha:
        required: true
        type: string
      base_branch:
        required: false
        type: string
        default: qcom-next-staging
      pr_number:
        type: string
        required: false

jobs:
  checker:
    runs-on:
      group: GHA-Kernel-SelfHosted-RG
      labels: [self-hosted, kernel-prd-u2404-x64-large-od-ephem]

    steps:
      - name: Clone kmake-image
        run: |
          git clone https://github.com/qualcomm-linux/kmake-image.git

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: kmake-image:latest
          context: kmake-image
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout code
        uses: qualcomm-linux/kernel-checkers/.github/actions/sync@main
        with:
          base_branch: ${{ inputs.base_branch }}
          pr_number: ${{ inputs.pr_number }}

      - name: Clone kernel-checkers
        run: cd .. && git clone https://github.com/qualcomm-linux/kernel-checkers.git

      - name: Run kernel check
        run: |
          bash ../kernel-checkers/${{ inputs.check_name }}.sh --kernel-src ${{ inputs.kernel_src }} \
          --base ${{ inputs.base_sha }} --head ${{ inputs.head_sha }}
