name: Kernel Checkers
on:
  workflow_call:
    inputs:
      check_name:
        required: true
        type: string
      kernel_src:
        required: true
        type: string
      base_sha:
        required: true
        type: string
      head_sha:
        required: true
        type: string
      base_branch:
        required: false
        type: string
        default: qcom-next-staging
      pr_number:
        type: string
        required: false
      topic_repo:
        type: string
        required: false

jobs:
  checker:
    runs-on:
      group: GHA-Kernel-SelfHosted-RG
      labels: [self-hosted, kernel-prd-u2404-x64-large-od-ephem]

    steps:
      - name: Pull Docker Image
        run: |
          echo "Pulling Docker Image..."
          echo "::group::$(printf '__________ %-100s' 'Pull Image' | tr ' ' _)"
          docker pull artifacts.codelinaro.org/clo-420-qli-registry/kmake-image:ver.1.0
          docker tag artifacts.codelinaro.org/clo-420-qli-registry/kmake-image:ver.1.0 kmake-image:latest
          echo "::endgroup::"
          echo "Docker Image Pulled Successfully"

      - name: Checkout code
        uses: qualcomm-linux/kernel-checkers/.github/actions/sync@main
        with:
          base_branch: ${{ inputs.base_branch }}
          pr_number: ${{ inputs.pr_number }}
          topic_repo: ${{ inputs.topic_repo }}

      - name: Clone kernel-checkers
        run: cd .. && git clone https://github.com/qualcomm-linux/kernel-checkers.git

      - name: Run kernel check
        run: |
          bash ../kernel-checkers/${{ inputs.check_name }}.sh --kernel-src ${{ inputs.kernel_src }} \
          --base ${{ inputs.base_sha }} --head ${{ inputs.head_sha }}
